/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BillingGUI.java
 *
 * Created on Aug 25, 2014, 8:47:02 AM
 */
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;

/**
 *
 * @author Adithya
 */
public class BillingGUI extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    Cart c1 = new Cart();

    public BillingGUI() {
        initComponents();
    }

    /** Creates new form BillingGUI */
    public BillingGUI(Cart c2) {
        initComponents();
        c1 = c2;
        DefaultTableModel dtm = (DefaultTableModel) BillTable.getModel();
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM CART");
            int qnt = c1.getQuantity(), sk = c2.getStock();

            while (rs.next()) {
                double qnty = Double.parseDouble(rs.getString("QUANTITY"));
                String prdid = rs.getString("PRODUCTID"),
                        pty = rs.getString("PRODUCTTYPE"),
                        pr = Double.parseDouble(rs.getString("PRICE")) * qnty + "",
                        ct1 = rs.getString("CATEGORY");
                dtm.addRow(new String[]{prdid, pty, ct1, pr});
            }
            int len = c1.getProductType().length();
            sk = sk - qnt;
            String tablename;
            if (c1.getProductType().equals("Books")) {
                tablename = "BOOKS";
                rs = st.executeQuery("UPDATE " + tablename + "SET STOCK=" + sk + "WHERE PRODUCTID=" + c1.getProductID());
            } else if (len == 5) {
                tablename = "WATCH";
                rs = st.executeQuery("UPDATE " + tablename + "SET STOCK=" + sk + "WHERE PRODUCTID=" + c1.getProductID());
            } else if (len == 4) {
                tablename = "CLOTHING";
                rs = st.executeQuery("UPDATE " + tablename + "SET STOCK=" + sk + "WHERE PRODUCTID=" + c1.getProductID());
            }
            int i = BillTable.getRowCount();
            double totprice = 0, va1;
            for (int temp = 0; temp < i; temp++) {
                String val = dtm.getValueAt(temp, 3).toString();
                va1 = Double.parseDouble(val);
                totprice = totprice + va1;
            }
            amountpayableTextField.setText(totprice + "");
            rs.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            try {
                double amtpayable = Double.parseDouble(amountpayableTextField.getText());
                String sql = "DELETE FROM CART;";
                int i = st.executeUpdate(sql);
                if (i > 0); else if (i < 0) {
                    JOptionPane.showMessageDialog(this, "Error not cart cleared");
                }
            } catch (Exception e1) {
                JOptionPane.showMessageDialog(null, e1.getMessage());
            }
            System.exit(0);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        amountpayableTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PurchaseButton = new javax.swing.JButton();
        ContinueShoppingButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banner-online.jpg"))); // NOI18N
        jLabel1.setText("Billing");
        jLabel1.setMinimumSize(new java.awt.Dimension(250, 100));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -20, 740, 160));

        amountpayableTextField.setEditable(false);
        amountpayableTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountpayableTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(amountpayableTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 136, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Amount Payable : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, -1, -1));

        PurchaseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QQQQ.JPG"))); // NOI18N
        PurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PurchaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 110, -1));

        ContinueShoppingButton.setBackground(new java.awt.Color(153, 153, 255));
        ContinueShoppingButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground"));
        ContinueShoppingButton.setText("Continue Shopping");
        ContinueShoppingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueShoppingButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ContinueShoppingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 171, -1));

        BillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCTID", "Product", "Author/Brand", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BillTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 660, 211));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xxzz.JPG"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 660, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ppp.JPG"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 640, 340));

        jLabel5.setBackground(new java.awt.Color(255, 102, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bbbbb.JPG"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 660, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private void ContinueShoppingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueShoppingButtonActionPerformed
            // TODO add your handling code here:
            new ShoppingGUI().setVisible(true);


            this.dispose();
    }//GEN-LAST:event_ContinueShoppingButtonActionPerformed

        private void PurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseButtonActionPerformed
            // TODO add your handling code here:
            try {
                double amtpayable = Double.parseDouble(amountpayableTextField.getText());
                String sql = "DELETE FROM CART;";
                int i = st.executeUpdate(sql);
                if (i > 0); else if (i < 0) {
                    JOptionPane.showMessageDialog(this, "Error not cart cleared");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }//GEN-LAST:event_PurchaseButtonActionPerformed

        private void amountpayableTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountpayableTextFieldActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_amountpayableTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BillingGUI().setVisible(true);


            }
        });


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BillTable;
    private javax.swing.JButton ContinueShoppingButton;
    private javax.swing.JButton PurchaseButton;
    private javax.swing.JTextField amountpayableTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
