/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WatchGUI.java
 *
 * Created on Aug 25, 2014, 8:43:41 AM
 */
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;

/**
 *
 * @author Adithya
 */
public class WatchGUI extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    Cart c1 = new Cart();

    /** Creates new form WatchGUI */
    public WatchGUI() {
        initComponents();

        ConsolidatedSearchButton.setEnabled(false);
        SearchButton.setEnabled(false);
        AddToCartButton.setVisible(false);
        DefaultTableModel dtm = (DefaultTableModel) WatchTable.getModel();
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM  WATCH");
            while (rs.next()) {
                String prdid = rs.getString("PRODUCTID"),
                        bn = rs.getString("BRANDNAME"),
                        pr = rs.getString("PRICE"),
                        st = rs.getString("STOCK"),
                        make = rs.getString("MAKE"),
                        cl = rs.getString("COLOUR"),
                        cat1 = rs.getString("CATEGORY1"),
                        cat2 = rs.getString("CATEGORY2");
                dtm.addRow(new String[]{prdid, bn, make, cl, cat1});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.exit(0);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        brandnameTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        typeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        prdidTextField = new javax.swing.JTextField();
        colourTextField = new javax.swing.JTextField();
        stockTextField = new javax.swing.JTextField();
        categoryTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        WatchTable = new javax.swing.JTable();
        priceTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        strapTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AddToCartButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        ConsolidatedSearchButton = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        RefreshButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brandnameTextField.setEditable(false);
        jPanel1.add(brandnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 140, -1));

        jLabel15.setForeground(new java.awt.Color(51, 102, 255));
        jLabel15.setText("help:");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 30, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wathc.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 820, 140));

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Stock");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        typeTextField.setEditable(false);
        jPanel1.add(typeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 140, -1));

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Colour");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, -1, -1));

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        prdidTextField.setEditable(false);
        jPanel1.add(prdidTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 140, -1));

        colourTextField.setEditable(false);
        jPanel1.add(colourTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 140, -1));

        stockTextField.setEditable(false);
        jPanel1.add(stockTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 140, -1));

        categoryTextField.setEditable(false);
        jPanel1.add(categoryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 140, -1));

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Category");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, -1));

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Strap");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, -1, -1));

        WatchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Brand Name", "make", "colour", "type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        WatchTable.setColumnSelectionAllowed(true);
        WatchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WatchTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(WatchTable);
        WatchTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 309, 560, 290));

        priceTextField.setEditable(false);
        jPanel1.add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 140, -1));

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Brand Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        strapTextField.setEditable(false);
        jPanel1.add(strapTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 140, -1));

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        AddToCartButton.setText("Add to cart");
        AddToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddToCartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 127, 30));

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 131, 31));

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("PRODUCT ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 312, -1, -1));

        BackButton.setBackground(new java.awt.Color(255, 255, 255));
        BackButton.setText("back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, -1));

        ConsolidatedSearchButton.setText("display consolidated search");
        ConsolidatedSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsolidatedSearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConsolidatedSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 202, 31));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 42, -1));

        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Quantity");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xxzz.JPG"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 820, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banner-online.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 780, 110));

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RefreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 90, 30));

        jLabel14.setFont(new java.awt.Font("Agency FB", 0, 48));
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Choose your watches!");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 420, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bbbbb.JPG"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        AddToCartButton.setVisible(true);
        ConsolidatedSearchButton.setEnabled(false);
        SearchButton.setEnabled(false);

        try {
            DefaultTableModel dtm1 = (DefaultTableModel) WatchTable.getModel();
            int i = WatchTable.getSelectedRow();
            int j = WatchTable.getSelectedColumn();
            String value = dtm1.getValueAt(i, j).toString();
            String v = dtm1.getValueAt(i, 0).toString();

            if (j == 0) {
                String SQL = "SELECT * FROM WATCH "
                        + " WHERE PRODUCTID LIKE " + value;
                System.out.print(SQL);
                rs = st.executeQuery(SQL);
                if (rs.next()) {
                    prdidTextField.setText(rs.getString("PRODUCTID"));
                    brandnameTextField.setText(rs.getString("BRANDNAME"));
                    priceTextField.setText(rs.getString("PRICE"));
                    stockTextField.setText(rs.getString("STOCK"));
                    typeTextField.setText(rs.getString("MAKE"));
                    colourTextField.setText(rs.getString("COLOUR"));
                    categoryTextField.setText(rs.getString("CATEGORY1"));
                    strapTextField.setText(rs.getString("CATEGORY2"));
                }
            } else if (j == 1) {
                String SQL = "SELECT * FROM WATCH "
                        + " WHERE BRANDNAME LIKE '" + value + "'AND PRODUCTID = " + v;
                rs = st.executeQuery(SQL);
                if (rs.next()) {
                    prdidTextField.setText(rs.getString("PRODUCTID"));
                    brandnameTextField.setText(rs.getString("BRANDNAME"));
                    priceTextField.setText(rs.getString("PRICE"));
                    stockTextField.setText(rs.getString("STOCK"));
                    typeTextField.setText(rs.getString("MAKE"));
                    colourTextField.setText(rs.getString("COLOUR"));
                    categoryTextField.setText(rs.getString("CATEGORY1"));
                    strapTextField.setText(rs.getString("CATEGORY2"));
                }
            } else if (j == 2) {
                String SQL = "SELECT * FROM WATCH "
                        + " WHERE MAKE LIKE '" + value + "'AND PRODUCTID = " + v;
                rs = st.executeQuery(SQL);
                if (rs.next()) {
                    prdidTextField.setText(rs.getString("PRODUCTID"));
                    brandnameTextField.setText(rs.getString("BRANDNAME"));
                    priceTextField.setText(rs.getString("PRICE"));
                    stockTextField.setText(rs.getString("STOCK"));
                    typeTextField.setText(rs.getString("MAKE"));
                    colourTextField.setText(rs.getString("COLOUR"));
                    categoryTextField.setText(rs.getString("CATEGORY1"));
                    strapTextField.setText(rs.getString("CATEGORY2"));
                }
            } else if (j == 3) {
                String SQL = "SELECT * FROM WATCH "
                        + " WHERE COLOUR LIKE '" + value + "'AND PRODUCTID LIKE " + v;
                rs = st.executeQuery(SQL);
                if (rs.next()) {
                    prdidTextField.setText(rs.getString("PRODUCTID"));
                    brandnameTextField.setText(rs.getString("BRANDNAME"));
                    priceTextField.setText(rs.getString("PRICE"));
                    stockTextField.setText(rs.getString("STOCK"));
                    typeTextField.setText(rs.getString("MAKE"));
                    colourTextField.setText(rs.getString("COLOUR"));
                    categoryTextField.setText(rs.getString("CATEGORY1"));
                    strapTextField.setText(rs.getString("CATEGORY2"));
                }
            } else if (j == 4) {
                String SQL = "SELECT * FROM WATCH "
                        + " WHERE CATEGORY1 LIKE '" + value + "'AND PRODUCTID LIKE " + v;
                rs = st.executeQuery(SQL);
                if (rs.next()) {
                    prdidTextField.setText(rs.getString("PRODUCTID"));
                    brandnameTextField.setText(rs.getString("BRANDNAME"));
                    priceTextField.setText(rs.getString("PRICE"));
                    stockTextField.setText(rs.getString("STOCK"));
                    typeTextField.setText(rs.getString("MAKE"));
                    colourTextField.setText(rs.getString("COLOUR"));
                    categoryTextField.setText(rs.getString("CATEGORY1"));
                    strapTextField.setText(rs.getString("CATEGORY2"));
                }
            } else {
                JOptionPane.showMessageDialog(null, "NO RECORD FOUND");
            }



        } catch (Exception e) {
            System.out.println("ERROR! " + e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void AddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartButtonActionPerformed
        // TODO add your handling code here:
        try {
            String prid = prdidTextField.getText(), bname = brandnameTextField.getText(), prty = typeTextField.getText(), price = priceTextField.getText(), ct1 = categoryTextField.getText(), qnty = jSpinner1.getValue().toString();
            c1.setProductID(Integer.parseInt(prid));
            c1.setProductType("WATCH" + prty);
            c1.setPrice(Double.parseDouble(price));
            c1.setStock(Integer.parseInt(stockTextField.getText()));
            c1.setCategory1(ct1);
            c1.setBrandName(bname);
            c1.setCategory2(strapTextField.getText());
            c1.setColour(colourTextField.getText());
            c1.setQuantity(Integer.parseInt(jSpinner1.getValue().toString()));
            if (c1.getQuantity() <= 0) {
                JOptionPane.showMessageDialog(null, "PLEASE SET THE NUMBER OF ITEMS");
            } else {
                String sql = "INSERT INTO CART VALUES (" + prid + ",'" + bname + "','" + ct1 + "'," + price + "," + qnty + ");";

                if (JOptionPane.showConfirmDialog(null, "Are you sure you want to add to cart?") == JOptionPane.YES_OPTION) {
                    int n = st.executeUpdate(sql);
                    if (n > 0) {
                        JOptionPane.showMessageDialog(this, "Successfully added to Cart!" + "\n" + "Please check your cart.");
                    } else {
                        JOptionPane.showMessageDialog(null, "ERROR ADDING TO CART! ");
                    }
                    new CartGUI(c1).setVisible(true);
                    this.dispose();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_AddToCartButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        new ShoppingGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ConsolidatedSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsolidatedSearchButtonActionPerformed
        // TODO add your handling code here:

        ConsolidatedSearchButton.setEnabled(false);
        SearchButton.setEnabled(false);
        DefaultTableModel dtm1 = (DefaultTableModel) WatchTable.getModel();

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            st = con.createStatement();
            int i = WatchTable.getSelectedRow();
            int j = WatchTable.getSelectedColumn();
            String value = dtm1.getValueAt(i, j).toString();
            int rowcnt = dtm1.getRowCount();
            for (int k = 0; k < rowcnt; k++) {
                dtm1.removeRow(0);
            }
            if (j == 1) {
                String SQL = "SELECT * FROM WATCH "
                        + " WHERE BRANDNAME LIKE '" + value + "'";
                System.out.print(SQL);
                rs = st.executeQuery(SQL);
                while (rs.next()) {
                    String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), make = rs.getString("MAKE"), cl = rs.getString("COLOUR"), cat1 = rs.getString("CATEGORY1"), cat2 = rs.getString("CATEGORY2");
                    dtm1.addRow(new String[]{prdid, bn, make, cl, cat1});
                }

            } else if (j == 2) {
                String SQL = "SELECT * FROM WATCH "
                        + " WHERE MAKE LIKE '" + value + "'";
                System.out.print(SQL);
                rs = st.executeQuery(SQL);
                while (rs.next()) {
                    String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), make = rs.getString("MAKE"), cl = rs.getString("COLOUR"), cat1 = rs.getString("CATEGORY1"), cat2 = rs.getString("CATEGORY2");
                    dtm1.addRow(new String[]{prdid, bn, make, cl, cat1});
                }

            } else if (j == 3) {
                String SQL = "SELECT * FROM WATCH "
                        + " WHERE COLOUR LIKE '" + value + "'";
                System.out.print(SQL);
                rs = st.executeQuery(SQL);
                while (rs.next()) {
                    String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), make = rs.getString("MAKE"), cl = rs.getString("COLOUR"), cat1 = rs.getString("CATEGORY1"), cat2 = rs.getString("CATEGORY2");
                    dtm1.addRow(new String[]{prdid, bn, make, cl, cat1});
                }

            } else if (j == 4) {
                String SQL = "SELECT * FROM WATCH "
                        + " WHERE CATEGORY1 LIKE '" + value + "'";
                System.out.print(SQL);
                rs = st.executeQuery(SQL);
                while (rs.next()) {
                    String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), make = rs.getString("MAKE"), cl = rs.getString("COLOUR"), cat1 = rs.getString("CATEGORY1"), cat2 = rs.getString("CATEGORY2");
                    dtm1.addRow(new String[]{prdid, bn, make, cl, cat1});
                }

            } else {
                JOptionPane.showMessageDialog(null, "NO RECORD FOUND");
            }

            rs.close();

        } catch (Exception e) {
            System.out.println("ERROR! " + e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_ConsolidatedSearchButtonActionPerformed

    private void WatchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WatchTableMouseClicked
        // TODO add your handling code here:
        ConsolidatedSearchButton.setEnabled(true);
        SearchButton.setEnabled(true);

    }//GEN-LAST:event_WatchTableMouseClicked

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:

        ConsolidatedSearchButton.setEnabled(false);
        SearchButton.setEnabled(false);
        DefaultTableModel dtm = (DefaultTableModel) WatchTable.getModel();
        int rowcnt = dtm.getRowCount();
        for (int k = 0; k < rowcnt; k++) {
            dtm.removeRow(0);
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM  WATCH");
            rs = st.executeQuery("SELECT * FROM  WATCH");
            while (rs.next()) {
                String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), make = rs.getString("MAKE"), cl = rs.getString("COLOUR"), cat1 = rs.getString("CATEGORY1"), cat2 = rs.getString("CATEGORY2");
                dtm.addRow(new String[]{prdid, bn, make, cl, cat1});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Please choose the item you wish to “buy” from the displayed Table and click" + "\n"
                + " 'Search' button if you want to know the other details of the item chosen (clicked)." + "\n"
                + " 'Consolidated Search' button if you want us to display all the items with that particular field." + "\n"
                + " Once that’s done you can either place your item in your cart or you can choose another item from the table by clicking the “Refresh” button.");

    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WatchGUI().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ConsolidatedSearchButton;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTable WatchTable;
    private javax.swing.JTextField brandnameTextField;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JTextField colourTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField prdidTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField stockTextField;
    private javax.swing.JTextField strapTextField;
    private javax.swing.JTextField typeTextField;
    // End of variables declaration//GEN-END:variables
}
