/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CartGUI.java
 *
 * Created on Aug 24, 2014, 12:35:41 PM
 */
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;

/**
 *
 * @author Adithya
 */
public class CartGUI extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    Cart c2 = new Cart();

    /** Creates new form CartGUI */
    public CartGUI() {
        initComponents();
    }

    public CartGUI(Cart c1) {
        initComponents();
        c2 = c1;

        DefaultTableModel dtm = (DefaultTableModel) CartTable.getModel();
        {
            int rowcnt = dtm.getRowCount();
            for (int k = 0; k < rowcnt; k++) {
                dtm.removeRow(0);
            }
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            st = con.createStatement();

            rs = st.executeQuery("SELECT * FROM CART");
            int qnt = c1.getQuantity();
            while (rs.next()) {
                String prdid = rs.getString("PRODUCTID"), pty = rs.getString("PRODUCTTYPE"), pr = rs.getString("PRICE"), ct1 = rs.getString("CATEGORY"), qnty = rs.getString("QUANTITY");
                dtm.addRow(new String[]{prdid, pty, ct1, pr, qnty});
            }
            c1.setQuantity(qnt);
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            try {
                String sql = "DELETE FROM CART;";
                int i = st.executeUpdate(sql);
                if (i > 0); else if (i < 0) {
                    JOptionPane.showMessageDialog(this, "Error not cart cleared");
                }
            } catch (Exception e1) {
                JOptionPane.showMessageDialog(null, e1.getMessage());
            }
            System.exit(0);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CartTable = new javax.swing.JTable();
        BillButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        ContinueShoppingButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Product Name", "Category", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CartTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(CartTable);
        CartTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 740, 282));

        BillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WWW.JPG"))); // NOI18N
        BillButton.setText("Bill");
        BillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 157, 30));

        ResetButton.setText("Reset Cart");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 171, -1));

        ContinueShoppingButton.setText("Continue shopping");
        ContinueShoppingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueShoppingButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ContinueShoppingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 178, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banner-online.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 745, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cart.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 740, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xxzz.JPG"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 740, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/black.JPG"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 740, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContinueShoppingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueShoppingButtonActionPerformed
        // TODO add your handling code here:
        new ShoppingGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ContinueShoppingButtonActionPerformed

    private void BillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillButtonActionPerformed
        // TODO add your handling code here:

        new BillingGUI(c2).setVisible(true);
        new LoginGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BillButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        try {
            st.execute("DELETE FROM CART");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        DefaultTableModel dtm1 = (DefaultTableModel) CartTable.getModel();
        {
            int rowcnt = dtm1.getRowCount();
            for (int k = 0; k < rowcnt; k++) {
                dtm1.removeRow(0);
            }
        }
    }//GEN-LAST:event_ResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CartGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BillButton;
    private javax.swing.JTable CartTable;
    private javax.swing.JButton ContinueShoppingButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
