/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClothingGUI.java
 *
 * Created on Aug 24, 2014, 12:15:11 PM
 */
import javax.swing.*;
import javax.swing.table.*;
import java.sql.*;

/**
 *
 * @author Adithya
 */
public class ClothingGUI extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    Cart c1 = new Cart();

    /** Creates new form ClothingGUI */
    public ClothingGUI() {
        initComponents();
        ConsolidatedSearchButton.setEnabled(false);
        SearchButton.setEnabled(false);
        AddToCartButton.setVisible(false);

        DefaultTableModel dtm = (DefaultTableModel) ClothingTable.getModel();
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM  CLOTHING");
            while (rs.next()) {
                String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), wear = rs.getString("WEAR"), col = rs.getString("COLOUR"), size = rs.getString("SIZE"), cat = rs.getString("CATEGORY");
                dtm.addRow(new String[]{prdid, bn, wear, col, cat});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.exit(0);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClothingTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        prdidTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stockTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        brandnameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sizeTextField = new javax.swing.JTextField();
        colourTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        typeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        AddToCartButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ConsolidatedSearchButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        RefreshButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClothingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "BrandName", "Type", "colour", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ClothingTable.setColumnSelectionAllowed(true);
        ClothingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClothingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ClothingTable);
        ClothingTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 326, 580, 320));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 102, 255));
        jLabel14.setText("help:?");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, -1));

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Category");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 70, -1));

        prdidTextField.setEditable(false);
        jPanel1.add(prdidTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 130, -1));

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Colour");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 60, -1));

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Size");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 50, -1));

        stockTextField.setEditable(false);
        jPanel1.add(stockTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 130, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ladies-clothing-store-interior-decoration-view.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 820, 140));

        brandnameTextField.setEditable(false);
        jPanel1.add(brandnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 130, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRODUCT ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 90, -1));

        priceTextField.setEditable(false);
        jPanel1.add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 130, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Brand Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 90, -1));

        categoryTextField.setEditable(false);
        jPanel1.add(categoryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 130, -1));

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 50, -1));

        sizeTextField.setEditable(false);
        jPanel1.add(sizeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 130, -1));

        colourTextField.setEditable(false);
        jPanel1.add(colourTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 130, -1));

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 50, -1));

        typeTextField.setEditable(false);
        jPanel1.add(typeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 130, -1));

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Stock");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 50, -1));

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, 120, 30));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, 40, -1));

        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Quantity");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 70, -1));

        AddToCartButton.setText("Add to cart");
        AddToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddToCartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 130, 30));

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banner-online.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 780, 120));

        ConsolidatedSearchButton.setText("Display consolidated search");
        ConsolidatedSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsolidatedSearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConsolidatedSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, 200, 30));

        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 48));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Choose your clothes !");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 410, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xxzz.JPG"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 820, 110));

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RefreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, -1, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bbbbb.JPG"))); // NOI18N
        jLabel16.setText("jLabel12");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 810, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        AddToCartButton.setVisible(true);
        ConsolidatedSearchButton.setEnabled(false);
        SearchButton.setEnabled(false);
        try {
            DefaultTableModel dtm1 = (DefaultTableModel) ClothingTable.getModel();
            int i = ClothingTable.getSelectedRow();
            int j = ClothingTable.getSelectedColumn();
            String value = dtm1.getValueAt(i, j).toString();
            if (j == 0) {
                String SQL = "SELECT * FROM CLOTHING "
                        + " WHERE PRODUCTID LIKE " + value;
                rs = st.executeQuery(SQL);
                if (rs.next()) {
                    prdidTextField.setText(rs.getString("PRODUCTID"));
                    brandnameTextField.setText(rs.getString("BRANDNAME"));
                    priceTextField.setText(rs.getString("PRICE"));
                    stockTextField.setText(rs.getString("STOCK"));
                    typeTextField.setText(rs.getString("WEAR"));
                    colourTextField.setText(rs.getString("COLOUR"));
                    sizeTextField.setText(rs.getString("SIZE"));
                    categoryTextField.setText(rs.getString("CATEGORY2"));
                }
            } else if (j == 1) {
                String val;
                val = dtm1.getValueAt(i, 0).toString();
                String SQL = "SELECT * FROM CLOTHING "
                        + " WHERE BRANDNAME LIKE '" + value + "'AND PRODUCTID= " + val;
                rs = st.executeQuery(SQL);
                if (rs.next()) {
                    prdidTextField.setText(rs.getString("PRODUCTID"));
                    brandnameTextField.setText(rs.getString("BRANDNAME"));
                    priceTextField.setText(rs.getString("PRICE"));
                    stockTextField.setText(rs.getString("STOCK"));
                    typeTextField.setText(rs.getString("WEAR"));
                    colourTextField.setText(rs.getString("COLOUR"));
                    sizeTextField.setText(rs.getString("SIZE"));
                    categoryTextField.setText(rs.getString("CATEGORY"));
                }
            } else if (j == 2) {
                String val;
                val = dtm1.getValueAt(i, 0).toString();
                String SQL = "SELECT * FROM CLOTHING "
                        + " WHERE WEAR LIKE '" + value + "'" + "AND PRODUCTID=" + val;
                rs = st.executeQuery(SQL);
                if (rs.next()) {
                    prdidTextField.setText(rs.getString("PRODUCTID"));
                    brandnameTextField.setText(rs.getString("BRANDNAME"));
                    priceTextField.setText(rs.getString("PRICE"));
                    stockTextField.setText(rs.getString("STOCK"));
                    typeTextField.setText(rs.getString("WEAR"));
                    colourTextField.setText(rs.getString("COLOUR"));
                    sizeTextField.setText(rs.getString("SIZE"));
                    categoryTextField.setText(rs.getString("CATEGORY"));
                }
            } else if (j == 3) {
                String val;
                val = dtm1.getValueAt(i, 0).toString();
                String SQL = "SELECT * FROM CLOTHING "
                        + " WHERE COLOUR LIKE '" + value + "'" + "AND PRODUCTID=" + val;
                rs = st.executeQuery(SQL);
                if (rs.next()) {
                    prdidTextField.setText(rs.getString("PRODUCTID"));
                    brandnameTextField.setText(rs.getString("BRANDNAME"));
                    priceTextField.setText(rs.getString("PRICE"));
                    stockTextField.setText(rs.getString("STOCK"));
                    typeTextField.setText(rs.getString("WEAR"));
                    colourTextField.setText(rs.getString("COLOUR"));
                    sizeTextField.setText(rs.getString("SIZE"));
                    categoryTextField.setText(rs.getString("CATEGORY"));
                }
            } else if (j == 4) {
                String val;
                val = dtm1.getValueAt(i, 0).toString();
                String SQL = "SELECT * FROM CLOTHING "
                        + " WHERE CATEGORY LIKE '" + value + "'" + "AND PRODUCTID=" + val;
                rs = st.executeQuery(SQL);
                if (rs.next()) {
                    prdidTextField.setText(rs.getString("PRODUCTID"));
                    brandnameTextField.setText(rs.getString("BRANDNAME"));
                    priceTextField.setText(rs.getString("PRICE"));
                    stockTextField.setText(rs.getString("STOCK"));
                    typeTextField.setText(rs.getString("WEAR"));
                    colourTextField.setText(rs.getString("COLOUR"));
                    sizeTextField.setText(rs.getString("SIZE"));
                    categoryTextField.setText(rs.getString("CATEGORY"));
                }

            } else {
                JOptionPane.showMessageDialog(null, "NO RECORD FOUND");
            }
            rs.close();
        } catch (Exception e) {
            System.out.println("ERROR! " + e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void AddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartButtonActionPerformed
        // TODO add your handling code here:
        try {
            String prid = prdidTextField.getText(), bname = brandnameTextField.getText(), prty = typeTextField.getText(), price = priceTextField.getText(), ct1 = sizeTextField.getText(), qnty = jSpinner1.getValue().toString();
            c1.setProductID(Integer.parseInt(prid));
            c1.setProductType("WEAR" + prty);
            c1.setPrice(Double.parseDouble(price));
            c1.setStock(Integer.parseInt(stockTextField.getText()));
            c1.setCategory1(ct1);
            c1.setBrandName(bname);
            c1.setCategory2(categoryTextField.getText());
            c1.setAuthor(colourTextField.getText());
            c1.setQuantity(Integer.parseInt(jSpinner1.getValue().toString()));
            if (c1.getQuantity() <= 0) {
                JOptionPane.showMessageDialog(this, "PLEASE SET THE NUMBER OF ITEMS");
            } else {
                String sql = "INSERT INTO CART VALUES (" + prid + ",'" + bname + "','" + ct1 + "'," + price + "," + qnty + ");";


                if (JOptionPane.showConfirmDialog(null, "Are you sure you want to add to cart?") == JOptionPane.YES_OPTION) {
                    int n = st.executeUpdate(sql);
                    if (n > 0) {
                        JOptionPane.showMessageDialog(this, "Successfully added to Cart!" + "\n" + "Please check your cart.");
                    } else {
                        JOptionPane.showMessageDialog(null, "ERROR ADDING TO CART! ");
                    }
                    new CartGUI(c1).setVisible(true);
                    this.dispose();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.exit(0);
        }


    }//GEN-LAST:event_AddToCartButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        new ShoppingGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ConsolidatedSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsolidatedSearchButtonActionPerformed
        // TODO add your handling code here:


        ConsolidatedSearchButton.setEnabled(false);
        SearchButton.setEnabled(false);
        DefaultTableModel dtm1 = (DefaultTableModel) ClothingTable.getModel();
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            st = con.createStatement();
            int i = ClothingTable.getSelectedRow();
            int j = ClothingTable.getSelectedColumn();
            String value = dtm1.getValueAt(i, j).toString();
            int rowcnt = dtm1.getRowCount();
            for (int k = 0; k < rowcnt; k++) {
                dtm1.removeRow(0);
            }
            if (j == 0) {
                String SQL = "SELECT * FROM CLOTHING "
                        + " WHERE PRODUCTID LIKE '" + value + "'";
                System.out.print(SQL);
                rs = st.executeQuery(SQL);
                while (rs.next()) {
                    String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), wear = rs.getString("WEAR"), col = rs.getString("COLOUR"), size = rs.getString("SIZE"), cat = rs.getString("CATEGORY");
                    dtm1.addRow(new String[]{prdid, bn, wear, col, cat});
                }

            }
            if (j == 1) {
                String SQL = "SELECT * FROM CLOTHING "
                        + " WHERE BRANDNAME LIKE '" + value + "'";
                System.out.print(SQL);
                rs = st.executeQuery(SQL);
                while (rs.next()) {
                    String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), wear = rs.getString("WEAR"), col = rs.getString("COLOUR"), size = rs.getString("SIZE"), cat = rs.getString("CATEGORY");
                    dtm1.addRow(new String[]{prdid, bn, wear, col, cat});
                }

            } else if (j == 2) {
                String SQL = "SELECT * FROM CLOTHING "
                        + " WHERE WEAR LIKE '" + value + "'";
                System.out.print(SQL);
                rs = st.executeQuery(SQL);
                while (rs.next()) {
                    String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), wear = rs.getString("WEAR"), col = rs.getString("COLOUR"), size = rs.getString("SIZE"), cat = rs.getString("CATEGORY");
                    dtm1.addRow(new String[]{prdid, bn, wear, col, cat});
                }

            } else if (j == 3) {
                String SQL = "SELECT * FROM CLOTHING "
                        + " WHERE COLOUR LIKE '" + value + "'";
                System.out.print(SQL);
                rs = st.executeQuery(SQL);
                while (rs.next()) {
                    String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), wear = rs.getString("WEAR"), col = rs.getString("COLOUR"), size = rs.getString("SIZE"), cat = rs.getString("CATEGORY");
                    dtm1.addRow(new String[]{prdid, bn, wear, col, cat});
                }

            } else if (j == 4) {
                String SQL = "SELECT * FROM CLOTHING "
                        + " WHERE CATEGORY LIKE '" + value + "'";
                System.out.print(SQL);
                rs = st.executeQuery(SQL);
                while (rs.next()) {
                    String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), wear = rs.getString("WEAR"), col = rs.getString("COLOUR"), size = rs.getString("SIZE"), cat = rs.getString("CATEGORY");
                    dtm1.addRow(new String[]{prdid, bn, wear, col, cat});
                }

            } else {
                JOptionPane.showMessageDialog(null, "NO RECORD FOUND");
            }

            rs.close();

        } catch (Exception e) {
            System.out.println("ERROR! " + e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_ConsolidatedSearchButtonActionPerformed

    private void ClothingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClothingTableMouseClicked
        // TODO add your handling code here:
        ConsolidatedSearchButton.setEnabled(true);
        SearchButton.setEnabled(true);
    }//GEN-LAST:event_ClothingTableMouseClicked

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
        ConsolidatedSearchButton.setEnabled(false);
        SearchButton.setEnabled(false);
        DefaultTableModel dtm = (DefaultTableModel) ClothingTable.getModel();
        int rowcnt = dtm.getRowCount();
        for (int k = 0; k < rowcnt; k++) {
            dtm.removeRow(0);
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM  CLOTHING");
            while (rs.next()) {
                String prdid = rs.getString("PRODUCTID"), bn = rs.getString("BRANDNAME"), pr = rs.getString("PRICE"), st = rs.getString("STOCK"), wear = rs.getString("WEAR"), col = rs.getString("COLOUR"), size = rs.getString("SIZE"), cat = rs.getString("CATEGORY");
                dtm.addRow(new String[]{prdid, bn, wear, col, cat});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Please choose the item you wish to “buy” from the displayed Table and click" + "\n"
                + " 'Search' button if you want to know the other details of the item chosen (clicked)." + "\n"
                + " 'Consolidated Search' button if you want us to display all the items with that particular field." + "\n"
                + " Once that’s done you can either place your item in your cart or you can choose another item from the table by clicking the “Refresh” button.");

    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ClothingGUI().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JTable ClothingTable;
    private javax.swing.JButton ConsolidatedSearchButton;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField brandnameTextField;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JTextField colourTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField prdidTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField sizeTextField;
    private javax.swing.JTextField stockTextField;
    private javax.swing.JTextField typeTextField;
    // End of variables declaration//GEN-END:variables
}
