/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewItemsGUI.java
 *
 * Created on 24 Jan, 2015, 3:45:52 PM
 */
import javax.swing.*;

/**
 *
 * @author Adithya
 */
public class NewItemsGUI extends javax.swing.JFrame {

    /** Creates new form NewItemsGUI */
    public NewItemsGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newitemTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedbackTextArea = new javax.swing.JTextArea();
        DoneButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Overallviewofstore.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 264));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13));
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("New Item you'd like shop : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        newitemTextField.setText("                          Enter the new Item");
        newitemTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newitemTextFieldMouseClicked(evt);
            }
        });
        jPanel1.add(newitemTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 332, -1));

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 18));
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Give an Feedback and Ideas about new Items that is to be included!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13));
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Feedback:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        feedbackTextArea.setColumns(20);
        feedbackTextArea.setRows(5);
        feedbackTextArea.setText("Please give you feedback.. \nIt really matters a lot to us..\nEnter here!:\n\n\n\n\nThank you!");
        feedbackTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackTextAreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(feedbackTextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 330, 150));

        DoneButton.setText("Done! ");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, 134, 23));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 18));
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Please help us to serve you better!");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banner-online.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 114));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xxzz.JPG"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 670, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bbbbb.JPG"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 780, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        // TODO add your handling code here:
        try {
            String newit = newitemTextField.getText();
            String feedback = feedbackTextArea.getText();
            String sql = "INSERT INTO NEWIT VALUES(" + newit + "," + feedback + ");";
            JOptionPane.showMessageDialog(this, "THANK YOU FOR YOUR RESPONSE!");
            new ShoppingGUI().setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void feedbackTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackTextAreaMouseClicked
        // TODO add your handling code here:
        feedbackTextArea.setText("");
    }//GEN-LAST:event_feedbackTextAreaMouseClicked

    private void newitemTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newitemTextFieldMouseClicked
        // TODO add your handling code here:
        newitemTextField.setText("");
    }//GEN-LAST:event_newitemTextFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewItemsGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoneButton;
    private javax.swing.JTextArea feedbackTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newitemTextField;
    // End of variables declaration//GEN-END:variables
}
